services: 
  message-producer:
    build:
      context: .
      dockerfile: MessageProducer/Dockerfile
      target: final
    ports:
      - 3436:80
    depends_on: 
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80'
  counter:
    build:
      context: .
      dockerfile: CounterClient/Dockerfile
      target: final
    ports:
      - 3435:80
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80'
  filewriter:
    build:
      context: .
      dockerfile: WriteToFileClient/Dockerfile
      target: final
    ports:
      - 3434:80
    volumes:
      - ./WriteToFileClient:/home/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80'
  rabbitmq:
    image: rabbitmq:3.11.7-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
